// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khzsutwbkfzhuoxnqzjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoenN1dHdia2Z6aHVveG5xempoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDYzNjksImV4cCI6MjA2NDUyMjM2OX0.TgcWhlBy_qP4nOFrri4jU7T_U34glyQ74orCgF5YkNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});